In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Titanic.csv')

In [46]:
print(f'Null values in Age column: {data["Age"].isnull().sum()}')

Null values in Age column: 0

In [40]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

In [ ]:
data.drop(columns=['Cabin','Ticket'], inplace=True)

In [6]:
data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})
data.rename(columns={'Sex': 'Gender'}, inplace=True)

In [ ]:
female_business_class = data[(data['Gender'] == 1) & (data['Pclass'] == 1)]

In [ ]:
survived_passengers_in_business_class = data[(data['Survived'] == 1) & (data['Pclass'] == 1)]

In [ ]:
survival_rate_by_class = data.groupby('Pclass')['Survived'].mean()

In [13]:
filtered_data = data.loc[data['Age'] > 30, ['Name', 'Age', 'Fare']]
print('Passengers older than 30:')
filtered_data

Passengers older than 30:

                                                  Name   Age     Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
6                              McCarthy, Mr. Timothy J  54.0  51.8625
11                            Bonnell, Miss. Elizabeth  58.0  26.5500
..                                                 ...   ...      ...
873                        Vander Cruyssen, Mr. Victor  47.0   9.0000
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0  83.1583
881                                 Markun, Mr. Johann  33.0   7.8958
885               Rice, Mrs. William (Margaret Norton)  39.0  29.1250
890                                Dooley, Mr. Patrick  32.0   7.7500

[305 rows x 3 columns]

In [12]:
data['Family_Size'] = data['SibSp'] + data['Parch'] + 1
data

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Fare,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,7.2500,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,71.2833,C,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,53.1000,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,8.0500,S,1
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.000000,0,0,13.0000,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.000000,0,0,30.0000,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1,2,23.4500,S,4
889,890,1,1,"Behr, Mr. Karl Howell",0,26.000000,0,0,30.0000,C,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.000000,0,0,7.7500,Q,1

In [29]:
data['Title'] = data['Name'].str.split(',').str[1].str.split('.').str[0].str.strip()
data[['Title','Name']].head(50)

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
5       Mr                                   Moran, Mr. James
6       Mr                            McCarthy, Mr. Timothy J
7   Master                     Palsson, Master. Gosta Leonard
8      Mrs  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9      Mrs                Nasser, Mrs. Nicholas (Adele Achem)
10    Miss                    Sandstrom, Miss. Marguerite Rut
11    Miss                           Bonnell, Miss. Elizabeth
12      Mr                     Saundercock, Mr. William Henry
13      Mr                        Andersson, Mr. Anders Johan
14    Miss               Vestrom, Miss. Hulda Amanda Adolfina
15     Mrs                   Hewlett, Mrs. (Mary D Kingcome)
16  Master                               Rice, Master. Eugene
17      Mr                       Williams, Mr. Charles Eugene
18     Mrs  Vander Planke, Mrs. Julius (Emelia Maria Vande...
19     Mrs                            Masselmani, Mrs. Fatima
20      Mr                               Fynney, Mr. Joseph J
21      Mr                              Beesley, Mr. Lawrence
22    Miss                        McGowan, Miss. Anna "Annie"
23      Mr                       Sloper, Mr. William Thompson
24    Miss                      Palsson, Miss. Torborg Danira
25     Mrs  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
26      Mr                            Emir, Mr. Farred Chehab
27      Mr                     Fortune, Mr. Charles Alexander
28    Miss                      O'Dwyer, Miss. Ellen "Nellie"
29      Mr                                Todoroff, Mr. Lalio
30     Don                           Uruchurtu, Don. Manuel E
31     Mrs     Spencer, Mrs. William Augustus (Marie Eugenie)
32    Miss                           Glynn, Miss. Mary Agatha
33      Mr                              Wheadon, Mr. Edward H
34      Mr                            Meyer, Mr. Edgar Joseph
35      Mr                     Holverson, Mr. Alexander Oskar
36      Mr                                   Mamee, Mr. Hanna
37      Mr                           Cann, Mr. Ernest Charles
38    Miss                 Vander Planke, Miss. Augusta Maria
39    Miss                        Nicola-Yarred, Miss. Jamila
40     Mrs     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
41     Mrs  Turpin, Mrs. William John Robert (Dorothy Ann ...
42      Mr                                Kraeff, Mr. Theodor
43    Miss           Laroche, Miss. Simonne Marie Anne Andree
44    Miss                      Devaney, Miss. Margaret Delia
45      Mr                           Rogers, Mr. William John
46      Mr                                  Lennon, Mr. Denis
47    Miss                          O'Driscoll, Miss. Bridget
48      Mr                                Samaan, Mr. Youssef
49     Mrs      Arnold-Franchi, Mrs. Josef (Josefine Franchi)

In [52]:
data['Age']= data['Age'].astype(int)
# fill the 0 age with mean age
data['Age'] = data['Age'].replace(0, data['Age'].mean())
data[data['Age']==0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Gender, Age, SibSp, Parch, Fare, Embarked, Family_Size, Title, Age_Group]
Index: []

In [53]:
bins=[0, 12, 18, 60, 100]
labels=['Child', 'Teenager', 'Adult', 'Senior']
data['Age_Group'] = pd.cut(data['Age'],bins=bins, labels = labels)
data[data['Age']<=12 ][['Age','Age_Group']].head(30)

     Age Age_Group
7      2     Child
10     4     Child
16     2     Child
24     8     Child
43     3     Child
50     7     Child
58     5     Child
59    11     Child
63     4     Child
119    2     Child
125   12     Child
147    9     Child
164    1     Child
165    9     Child
171    4     Child
172    1     Child
182    9     Child
183    1     Child
184    4     Child
193    3     Child
205    2     Child
233    5     Child
237    8     Child
261    3     Child
278    7     Child
297    2     Child
340    2     Child
348    3     Child
374    3     Child
381    1     Child

In [48]:
print(f"null values in Age column: {data['Age'].isnull().sum()}")

null values in Age column: 0

In [51]:
# fill the 0 age with mean age
data['Age'] = data['Age'].replace(0, data['Age'].mean())
data[data['Age']==0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Gender, Age, SibSp, Parch, Fare, Embarked, Family_Size, Title, Age_Group]
Index: []